<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Tests;

class ClientFactory
{
    public static function create(HttpCallBackCatcher $httpCallback): \BoltAPILib\BoltAPIClient
    {
        $client = (new \BoltAPILib\BoltAPIClient(static::getConfigurationFromEnvironment()))
            ->withConfiguration(static::getTestConfiguration($httpCallback));
        return $client;
    }

    public static function getTestConfiguration(HttpCallBackCatcher $httpCallback): array
    {
        return ['httpCallback' => $httpCallback];
    }

    public static function getConfigurationFromEnvironment(): array
    {
        $config = [];
        $timeout = getenv('BOLT_API_LIB_TIMEOUT');
        $numberOfRetries = getenv('BOLT_API_LIB_NUMBER_OF_RETRIES');
        $maximumRetryWaitTime = getenv('BOLT_API_LIB_MAXIMUM_RETRY_WAIT_TIME');
        $xAPIKey = getenv('BOLT_API_LIB_X_API_KEY');
        $environment = getenv('BOLT_API_LIB_ENVIRONMENT');
        $accessToken = getenv('BOLT_API_LIB_ACCESS_TOKEN');

        if ($timeout !== false && \is_numeric($timeout)) {
            $config['timeout'] = intval($timeout);
        }

        if ($numberOfRetries !== false && \is_numeric($numberOfRetries)) {
            $config['numberOfRetries'] = intval($numberOfRetries);
        }

        if ($maximumRetryWaitTime !== false && \is_numeric($maximumRetryWaitTime)) {
            $config['maximumRetryWaitTime'] = intval($maximumRetryWaitTime);
        }

        if ($xAPIKey !== false) {
            $config['xAPIKey'] = $xAPIKey;
        }

        if ($environment !== false) {
            $config['environment'] = $environment;
        }

        if ($accessToken !== false) {
            $config['accessToken'] = $accessToken;
        }

        return $config;
    }
}
