<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Exceptions;

class TBDErrorException extends \BoltAPILib\Exceptions\ApiException
{
    /**
     * @var string|null
     */
    private $needsToBeDocumented;

    /**
     * Returns Needs to Be Documented.
     */
    public function getNeedsToBeDocumented(): ?string
    {
        return $this->needsToBeDocumented;
    }

    /**
     * Sets Needs to Be Documented.
     *
     * @maps needs_to_be_documented
     */
    public function setNeedsToBeDocumented(?string $needsToBeDocumented): void
    {
        $this->needsToBeDocumented = $needsToBeDocumented;
    }
}
