<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Exceptions;

class V1MerchantTransactionsVoid404ErrorException extends \BoltAPILib\Exceptions\ApiException
{
    /**
     * @var \BoltAPILib\Models\Result2|null
     */
    private $result;

    /**
     * @var \BoltAPILib\Models\Errors2[]|null
     */
    private $errors;

    /**
     * Returns Result.
     */
    public function getResult(): ?\BoltAPILib\Models\Result2
    {
        return $this->result;
    }

    /**
     * Sets Result.
     *
     * @maps result
     */
    public function setResult(?\BoltAPILib\Models\Result2 $result): void
    {
        $this->result = $result;
    }

    /**
     * Returns Errors.
     *
     * @return \BoltAPILib\Models\Errors2[]|null
     */
    public function getErrors(): ?array
    {
        return $this->errors;
    }

    /**
     * Sets Errors.
     *
     * @maps errors
     *
     * @param \BoltAPILib\Models\Errors2[]|null $errors
     */
    public function setErrors(?array $errors): void
    {
        $this->errors = $errors;
    }
}
