<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Exceptions;

class V1RemoteCheckoutOrder422ErrorException extends \BoltAPILib\Exceptions\ApiException
{
    /**
     * @var string|null
     */
    private $event;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var \BoltAPILib\Models\Error|null
     */
    private $error;

    /**
     * Returns Event.
     */
    public function getEvent(): ?string
    {
        return $this->event;
    }

    /**
     * Sets Event.
     *
     * @maps event
     */
    public function setEvent(?string $event): void
    {
        $this->event = $event;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @maps status
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Error.
     */
    public function getError(): ?\BoltAPILib\Models\Error
    {
        return $this->error;
    }

    /**
     * Sets Error.
     *
     * @maps error
     */
    public function setError(?\BoltAPILib\Models\Error $error): void
    {
        $this->error = $error;
    }
}
