<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

class ActionEnum
{
    public const SET_PASSWORD = 'set_password';

    public const ROTATE_PASSWORD = 'rotate_password';
}
