<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class AddressChangeView implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $ticketId;

    /**
     * @var AddressView|null
     */
    private $fromAddress;

    /**
     * @var AddressView|null
     */
    private $toAddress;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var int|null
     */
    private $timestamp;

    /**
     * Returns Ticket Id.
     */
    public function getTicketId(): ?string
    {
        return $this->ticketId;
    }

    /**
     * Sets Ticket Id.
     *
     * @maps ticket_id
     */
    public function setTicketId(?string $ticketId): void
    {
        $this->ticketId = $ticketId;
    }

    /**
     * Returns From Address.
     *
     * The address object returned in the response.
     */
    public function getFromAddress(): ?AddressView
    {
        return $this->fromAddress;
    }

    /**
     * Sets From Address.
     *
     * The address object returned in the response.
     *
     * @maps from_address
     */
    public function setFromAddress(?AddressView $fromAddress): void
    {
        $this->fromAddress = $fromAddress;
    }

    /**
     * Returns To Address.
     *
     * The address object returned in the response.
     */
    public function getToAddress(): ?AddressView
    {
        return $this->toAddress;
    }

    /**
     * Sets To Address.
     *
     * The address object returned in the response.
     *
     * @maps to_address
     */
    public function setToAddress(?AddressView $toAddress): void
    {
        $this->toAddress = $toAddress;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @maps status
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Timestamp.
     */
    public function getTimestamp(): ?int
    {
        return $this->timestamp;
    }

    /**
     * Sets Timestamp.
     *
     * @maps timestamp
     */
    public function setTimestamp(?int $timestamp): void
    {
        $this->timestamp = $timestamp;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->ticketId)) {
            $json['ticket_id']    = $this->ticketId;
        }
        if (isset($this->fromAddress)) {
            $json['from_address'] = $this->fromAddress;
        }
        if (isset($this->toAddress)) {
            $json['to_address']   = $this->toAddress;
        }
        if (isset($this->status)) {
            $json['status']       = $this->status;
        }
        if (isset($this->timestamp)) {
            $json['timestamp']    = $this->timestamp;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
