<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class AddressChangeRequestMetadataView implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $ticketId;

    /**
     * @var string|null
     */
    private $ticketStatus;

    /**
     * @var bool|null
     */
    private $canChangeShippingAddress;

    /**
     * Returns Id.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @maps status
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Ticket Id.
     */
    public function getTicketId(): ?string
    {
        return $this->ticketId;
    }

    /**
     * Sets Ticket Id.
     *
     * @maps ticket_id
     */
    public function setTicketId(?string $ticketId): void
    {
        $this->ticketId = $ticketId;
    }

    /**
     * Returns Ticket Status.
     */
    public function getTicketStatus(): ?string
    {
        return $this->ticketStatus;
    }

    /**
     * Sets Ticket Status.
     *
     * @maps ticket_status
     */
    public function setTicketStatus(?string $ticketStatus): void
    {
        $this->ticketStatus = $ticketStatus;
    }

    /**
     * Returns Can Change Shipping Address.
     */
    public function getCanChangeShippingAddress(): ?bool
    {
        return $this->canChangeShippingAddress;
    }

    /**
     * Sets Can Change Shipping Address.
     *
     * @maps can_change_shipping_address
     */
    public function setCanChangeShippingAddress(?bool $canChangeShippingAddress): void
    {
        $this->canChangeShippingAddress = $canChangeShippingAddress;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']                          = $this->id;
        }
        if (isset($this->status)) {
            $json['status']                      = $this->status;
        }
        if (isset($this->ticketId)) {
            $json['ticket_id']                   = $this->ticketId;
        }
        if (isset($this->ticketStatus)) {
            $json['ticket_status']               = $this->ticketStatus;
        }
        if (isset($this->canChangeShippingAddress)) {
            $json['can_change_shipping_address'] = $this->canChangeShippingAddress;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
