<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class AllianceDataInfo implements \JsonSerializable
{
    /**
     * @var string
     */
    private $callId;

    /**
     * @param string $callId
     */
    public function __construct(string $callId)
    {
        $this->callId = $callId;
    }

    /**
     * Returns Call Id.
     */
    public function getCallId(): string
    {
        return $this->callId;
    }

    /**
     * Sets Call Id.
     *
     * @required
     * @maps call_id
     */
    public function setCallId(string $callId): void
    {
        $this->callId = $callId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['call_id'] = $this->callId;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
