<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class AuthRejectionDetailsView implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $reasonCode;

    /**
     * @var string
     */
    private $reasonDescription;

    /**
     * @param string $reasonDescription
     */
    public function __construct(string $reasonDescription)
    {
        $this->reasonDescription = $reasonDescription;
    }

    /**
     * Returns Reason Code.
     */
    public function getReasonCode(): ?string
    {
        return $this->reasonCode;
    }

    /**
     * Sets Reason Code.
     *
     * @maps reason_code
     */
    public function setReasonCode(?string $reasonCode): void
    {
        $this->reasonCode = $reasonCode;
    }

    /**
     * Returns Reason Description.
     */
    public function getReasonDescription(): string
    {
        return $this->reasonDescription;
    }

    /**
     * Sets Reason Description.
     *
     * @required
     * @maps reason_description
     */
    public function setReasonDescription(string $reasonDescription): void
    {
        $this->reasonDescription = $reasonDescription;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->reasonCode)) {
            $json['reason_code']    = $this->reasonCode;
        }
        $json['reason_description'] = $this->reasonDescription;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
