<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

class AvsResponseEnum
{
    public const ENUM_00 = '00';

    public const ENUM_01 = '01';

    public const ENUM_02 = '02';

    public const ENUM_10 = '10';

    public const ENUM_11 = '11';

    public const ENUM_12 = '12';

    public const ENUM_13 = '13';

    public const ENUM_14 = '14';

    public const ENUM_20 = '20';

    public const ENUM_30 = '30';

    public const ENUM_31 = '31';

    public const ENUM_32 = '32';

    public const ENUM_33 = '33';

    public const ENUM_34 = '34';

    public const ENUM_40 = '40';

    public const ADYEN_ = 'adyen_';

    public const ADYEN_A = 'adyen_A';

    public const ADYEN_N = 'adyen_N';

    public const ADYEN_U = 'adyen_U';

    public const ADYEN_S = 'adyen_S';

    public const ADYEN_R = 'adyen_R';

    public const ADYEN_W = 'adyen_W';

    public const ADYEN_T = 'adyen_T';

    public const ADYEN_Z = 'adyen_Z';

    public const ADYEN_D = 'adyen_D';

    public const ADYEN_F = 'adyen_F';

    public const ADYEN_M = 'adyen_M';

    public const ADYEN_X = 'adyen_X';

    public const ADYEN_Y = 'adyen_Y';

    public const ADYEN_B = 'adyen_B';

    public const ADYEN_P = 'adyen_P';

    public const ADYEN_C = 'adyen_C';

    public const ADYEN_G = 'adyen_G';

    public const ADYEN_I = 'adyen_I';

    public const ADYEN_K = 'adyen_K';
}
