<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class CartDiscount implements \JsonSerializable
{
    /**
     * @var float|null
     */
    private $amount;

    /**
     * @var string|null
     */
    private $code;

    /**
     * @var string|null
     */
    private $reference;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var string|null
     */
    private $detailsUrl;

    /**
     * @var string|null
     */
    private $discountCategory;

    /**
     * @var int|null
     */
    private $type;

    /**
     * Returns Amount.
     */
    public function getAmount(): ?float
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     *
     * @maps amount
     */
    public function setAmount(?float $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Code.
     */
    public function getCode(): ?string
    {
        return $this->code;
    }

    /**
     * Sets Code.
     *
     * @maps code
     */
    public function setCode(?string $code): void
    {
        $this->code = $code;
    }

    /**
     * Returns Reference.
     *
     * Used to define the reference ID associated with the discount available.
     */
    public function getReference(): ?string
    {
        return $this->reference;
    }

    /**
     * Sets Reference.
     *
     * Used to define the reference ID associated with the discount available.
     *
     * @maps reference
     */
    public function setReference(?string $reference): void
    {
        $this->reference = $reference;
    }

    /**
     * Returns Description.
     *
     * Used to define the discount offering.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     *
     * Used to define the discount offering.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Details Url.
     *
     * Used to provide a link to additional details, such as a landing page, associated with the discount
     * offering.
     */
    public function getDetailsUrl(): ?string
    {
        return $this->detailsUrl;
    }

    /**
     * Sets Details Url.
     *
     * Used to provide a link to additional details, such as a landing page, associated with the discount
     * offering.
     *
     * @maps details_url
     */
    public function setDetailsUrl(?string $detailsUrl): void
    {
        $this->detailsUrl = $detailsUrl;
    }

    /**
     * Returns Discount Category.
     */
    public function getDiscountCategory(): ?string
    {
        return $this->discountCategory;
    }

    /**
     * Sets Discount Category.
     *
     * @maps discount_category
     */
    public function setDiscountCategory(?string $discountCategory): void
    {
        $this->discountCategory = $discountCategory;
    }

    /**
     * Returns Type.
     *
     * Used to define the type of discount applied to the cart, such as a percentage, dynamic, or flat
     * discount.
     */
    public function getType(): ?int
    {
        return $this->type;
    }

    /**
     * Sets Type.
     *
     * Used to define the type of discount applied to the cart, such as a percentage, dynamic, or flat
     * discount.
     *
     * @maps type
     */
    public function setType(?int $type): void
    {
        $this->type = $type;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->amount)) {
            $json['amount']            = $this->amount;
        }
        if (isset($this->code)) {
            $json['code']              = $this->code;
        }
        if (isset($this->reference)) {
            $json['reference']         = $this->reference;
        }
        if (isset($this->description)) {
            $json['description']       = $this->description;
        }
        if (isset($this->detailsUrl)) {
            $json['details_url']       = $this->detailsUrl;
        }
        if (isset($this->discountCategory)) {
            $json['discount_category'] = $this->discountCategory;
        }
        if (isset($this->type)) {
            $json['type']              = $this->type;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
