<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class CartItemExternalInputs implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $shopifyProductReference;

    /**
     * @var int|null
     */
    private $shopifyProductVariantReference;

    /**
     * @var int|null
     */
    private $shopifyLineItemReference;

    /**
     * Returns Shopify Product Reference.
     */
    public function getShopifyProductReference(): ?int
    {
        return $this->shopifyProductReference;
    }

    /**
     * Sets Shopify Product Reference.
     *
     * @maps shopify_product_reference
     */
    public function setShopifyProductReference(?int $shopifyProductReference): void
    {
        $this->shopifyProductReference = $shopifyProductReference;
    }

    /**
     * Returns Shopify Product Variant Reference.
     */
    public function getShopifyProductVariantReference(): ?int
    {
        return $this->shopifyProductVariantReference;
    }

    /**
     * Sets Shopify Product Variant Reference.
     *
     * @maps shopify_product_variant_reference
     */
    public function setShopifyProductVariantReference(?int $shopifyProductVariantReference): void
    {
        $this->shopifyProductVariantReference = $shopifyProductVariantReference;
    }

    /**
     * Returns Shopify Line Item Reference.
     */
    public function getShopifyLineItemReference(): ?int
    {
        return $this->shopifyLineItemReference;
    }

    /**
     * Sets Shopify Line Item Reference.
     *
     * @maps shopify_line_item_reference
     */
    public function setShopifyLineItemReference(?int $shopifyLineItemReference): void
    {
        $this->shopifyLineItemReference = $shopifyLineItemReference;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->shopifyProductReference)) {
            $json['shopify_product_reference']         = $this->shopifyProductReference;
        }
        if (isset($this->shopifyProductVariantReference)) {
            $json['shopify_product_variant_reference'] = $this->shopifyProductVariantReference;
        }
        if (isset($this->shopifyLineItemReference)) {
            $json['shopify_line_item_reference']       = $this->shopifyLineItemReference;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
