<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

/**
 * Used to determine the channel from which the order was created.
 */
class ChannelEnum
{
    public const BROWSER = 'browser';

    public const MOBILE_APP = 'mobile_app';
}
