<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class ConsumerSelfView implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $firstName;

    /**
     * @var string|null
     */
    private $lastName;

    /**
     * @var LoginView|null
     */
    private $authentication;

    /**
     * @var PhoneView[]|null
     */
    private $phones;

    /**
     * @var EmailView[]|null
     */
    private $emails;

    /**
     * @var bool|null
     */
    private $emailVerified;

    /**
     * @var bool|null
     */
    private $hasHadAssociatedAddress;

    /**
     * @var string|null
     */
    private $platformAccountStatus;

    /**
     * Returns Id.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns First Name.
     *
     * The given name of the person associated with this record.
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
     * Sets First Name.
     *
     * The given name of the person associated with this record.
     *
     * @maps first_name
     */
    public function setFirstName(?string $firstName): void
    {
        $this->firstName = $firstName;
    }

    /**
     * Returns Last Name.
     *
     * The surname of the person associated with this record.
     */
    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    /**
     * Sets Last Name.
     *
     * The surname of the person associated with this record.
     *
     * @maps last_name
     */
    public function setLastName(?string $lastName): void
    {
        $this->lastName = $lastName;
    }

    /**
     * Returns Authentication.
     */
    public function getAuthentication(): ?LoginView
    {
        return $this->authentication;
    }

    /**
     * Sets Authentication.
     *
     * @maps authentication
     */
    public function setAuthentication(?LoginView $authentication): void
    {
        $this->authentication = $authentication;
    }

    /**
     * Returns Phones.
     *
     * @return PhoneView[]|null
     */
    public function getPhones(): ?array
    {
        return $this->phones;
    }

    /**
     * Sets Phones.
     *
     * @maps phones
     *
     * @param PhoneView[]|null $phones
     */
    public function setPhones(?array $phones): void
    {
        $this->phones = $phones;
    }

    /**
     * Returns Emails.
     *
     * @return EmailView[]|null
     */
    public function getEmails(): ?array
    {
        return $this->emails;
    }

    /**
     * Sets Emails.
     *
     * @maps emails
     *
     * @param EmailView[]|null $emails
     */
    public function setEmails(?array $emails): void
    {
        $this->emails = $emails;
    }

    /**
     * Returns Email Verified.
     */
    public function getEmailVerified(): ?bool
    {
        return $this->emailVerified;
    }

    /**
     * Sets Email Verified.
     *
     * @maps email_verified
     */
    public function setEmailVerified(?bool $emailVerified): void
    {
        $this->emailVerified = $emailVerified;
    }

    /**
     * Returns Has Had Associated Address.
     */
    public function getHasHadAssociatedAddress(): ?bool
    {
        return $this->hasHadAssociatedAddress;
    }

    /**
     * Sets Has Had Associated Address.
     *
     * @maps has_had_associated_address
     */
    public function setHasHadAssociatedAddress(?bool $hasHadAssociatedAddress): void
    {
        $this->hasHadAssociatedAddress = $hasHadAssociatedAddress;
    }

    /**
     * Returns Platform Account Status.
     */
    public function getPlatformAccountStatus(): ?string
    {
        return $this->platformAccountStatus;
    }

    /**
     * Sets Platform Account Status.
     *
     * @maps platform_account_status
     */
    public function setPlatformAccountStatus(?string $platformAccountStatus): void
    {
        $this->platformAccountStatus = $platformAccountStatus;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']                         = $this->id;
        }
        if (isset($this->firstName)) {
            $json['first_name']                 = $this->firstName;
        }
        if (isset($this->lastName)) {
            $json['last_name']                  = $this->lastName;
        }
        if (isset($this->authentication)) {
            $json['authentication']             = $this->authentication;
        }
        if (isset($this->phones)) {
            $json['phones']                     = $this->phones;
        }
        if (isset($this->emails)) {
            $json['emails']                     = $this->emails;
        }
        if (isset($this->emailVerified)) {
            $json['email_verified']             = $this->emailVerified;
        }
        if (isset($this->hasHadAssociatedAddress)) {
            $json['has_had_associated_address'] = $this->hasHadAssociatedAddress;
        }
        if (isset($this->platformAccountStatus)) {
            $json['platform_account_status']    = $this->platformAccountStatus;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
