<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class CreditCardRefund implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $type;

    /**
     * @var int|null
     */
    private $date;

    /**
     * @var string|null
     */
    private $reference;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var CreditCardView|null
     */
    private $toCreditCard;

    /**
     * @var AmountView|null
     */
    private $amount;

    /**
     * @var CreditCardCreditView|null
     */
    private $credit;

    /**
     * @var TransactionSplitsView[]|null
     */
    private $splits;

    /**
     * Returns Id.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Type.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Date.
     */
    public function getDate(): ?int
    {
        return $this->date;
    }

    /**
     * Sets Date.
     *
     * @maps date
     */
    public function setDate(?int $date): void
    {
        $this->date = $date;
    }

    /**
     * Returns Reference.
     */
    public function getReference(): ?string
    {
        return $this->reference;
    }

    /**
     * Sets Reference.
     *
     * @maps reference
     */
    public function setReference(?string $reference): void
    {
        $this->reference = $reference;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @maps status
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns To Credit Card.
     *
     * The CreditCard object is used to to pay for guest-checkout transactions and save payment method
     * details to an account. Once saved, you can reference the associated `credit_card_id` for future
     * transactions.
     */
    public function getToCreditCard(): ?CreditCardView
    {
        return $this->toCreditCard;
    }

    /**
     * Sets To Credit Card.
     *
     * The CreditCard object is used to to pay for guest-checkout transactions and save payment method
     * details to an account. Once saved, you can reference the associated `credit_card_id` for future
     * transactions.
     *
     * @maps to_credit_card
     */
    public function setToCreditCard(?CreditCardView $toCreditCard): void
    {
        $this->toCreditCard = $toCreditCard;
    }

    /**
     * Returns Amount.
     */
    public function getAmount(): ?AmountView
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     *
     * @maps amount
     */
    public function setAmount(?AmountView $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Credit.
     */
    public function getCredit(): ?CreditCardCreditView
    {
        return $this->credit;
    }

    /**
     * Sets Credit.
     *
     * @maps credit
     */
    public function setCredit(?CreditCardCreditView $credit): void
    {
        $this->credit = $credit;
    }

    /**
     * Returns Splits.
     *
     * @return TransactionSplitsView[]|null
     */
    public function getSplits(): ?array
    {
        return $this->splits;
    }

    /**
     * Sets Splits.
     *
     * @maps splits
     *
     * @param TransactionSplitsView[]|null $splits
     */
    public function setSplits(?array $splits): void
    {
        $this->splits = $splits;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']             = $this->id;
        }
        if (isset($this->type)) {
            $json['type']           = $this->type;
        }
        if (isset($this->date)) {
            $json['date']           = $this->date;
        }
        if (isset($this->reference)) {
            $json['reference']      = $this->reference;
        }
        if (isset($this->status)) {
            $json['status']         = $this->status;
        }
        if (isset($this->toCreditCard)) {
            $json['to_credit_card'] = $this->toCreditCard;
        }
        if (isset($this->amount)) {
            $json['amount']         = $this->amount;
        }
        if (isset($this->credit)) {
            $json['credit']         = $this->credit;
        }
        if (isset($this->splits)) {
            $json['splits']         = $this->splits;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
