<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class CustomerListStatus implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $autoApproved;

    /**
     * @var bool|null
     */
    private $blockListed;

    /**
     * Returns Auto Approved.
     */
    public function getAutoApproved(): ?bool
    {
        return $this->autoApproved;
    }

    /**
     * Sets Auto Approved.
     *
     * @maps auto_approved
     */
    public function setAutoApproved(?bool $autoApproved): void
    {
        $this->autoApproved = $autoApproved;
    }

    /**
     * Returns Block Listed.
     */
    public function getBlockListed(): ?bool
    {
        return $this->blockListed;
    }

    /**
     * Sets Block Listed.
     *
     * @maps block_listed
     */
    public function setBlockListed(?bool $blockListed): void
    {
        $this->blockListed = $blockListed;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->autoApproved)) {
            $json['auto_approved'] = $this->autoApproved;
        }
        if (isset($this->blockListed)) {
            $json['block_listed']  = $this->blockListed;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
