<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class CustomFieldFullResponseView implements \JsonSerializable
{
    /**
     * @var CustomFieldView|null
     */
    private $field;

    /**
     * @var CustomFieldResponseView|null
     */
    private $response;

    /**
     * Returns Field.
     */
    public function getField(): ?CustomFieldView
    {
        return $this->field;
    }

    /**
     * Sets Field.
     *
     * @maps field
     */
    public function setField(?CustomFieldView $field): void
    {
        $this->field = $field;
    }

    /**
     * Returns Response.
     */
    public function getResponse(): ?CustomFieldResponseView
    {
        return $this->response;
    }

    /**
     * Sets Response.
     *
     * @maps response
     */
    public function setResponse(?CustomFieldResponseView $response): void
    {
        $this->response = $response;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->field)) {
            $json['field']    = $this->field;
        }
        if (isset($this->response)) {
            $json['response'] = $this->response;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
