<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use BoltAPILib\ApiHelper;
use stdClass;

class CustomFieldResponseView implements \JsonSerializable
{
    /**
     * @var string|null|bool
     */
    private $response;

    /**
     * Returns Response.
     *
     * @return string|null|bool
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Sets Response.
     *
     * @maps response
     * @mapsBy anyOf(string,bool,null)
     *
     * @param string|null|bool $response
     */
    public function setResponse($response): void
    {
        $this->response = $response;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->response)) {
            $json['response'] = $this->response;
        }

        ApiHelper::verifyClass($json, 'CustomFieldResponseView');
        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
