<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

/**
 * Used to define the source of the discount applied.
 */
class DiscountSourceEnum
{
    public const FRONTEND = 'frontend';

    public const DYNAMIC_DISCOUNT = 'dynamic_discount';
}
