<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

class HookTypeEnum
{
    public const ENUM_1 = 1;

    public const ENUM_2 = 2;

    public const ENUM_3 = 3;

    public const ENUM_4 = 4;

    public const ENUM_5 = 5;

    public const ENUM_6 = 6;
}
