<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class IAuthorizeResultView implements \JsonSerializable
{
    /**
     * @var TransactionView|null
     */
    private $transaction;

    /**
     * @var AuthorizeExternalOutputs|null
     */
    private $externalOutputs;

    /**
     * @var bool|null
     */
    private $isVerifiedDeviceSaved;

    /**
     * @var string|null
     */
    private $redirectUrl;

    /**
     * Returns Transaction.
     */
    public function getTransaction(): ?TransactionView
    {
        return $this->transaction;
    }

    /**
     * Sets Transaction.
     *
     * @maps transaction
     */
    public function setTransaction(?TransactionView $transaction): void
    {
        $this->transaction = $transaction;
    }

    /**
     * Returns External Outputs.
     */
    public function getExternalOutputs(): ?AuthorizeExternalOutputs
    {
        return $this->externalOutputs;
    }

    /**
     * Sets External Outputs.
     *
     * @maps external_outputs
     */
    public function setExternalOutputs(?AuthorizeExternalOutputs $externalOutputs): void
    {
        $this->externalOutputs = $externalOutputs;
    }

    /**
     * Returns Is Verified Device Saved.
     */
    public function getIsVerifiedDeviceSaved(): ?bool
    {
        return $this->isVerifiedDeviceSaved;
    }

    /**
     * Sets Is Verified Device Saved.
     *
     * @maps is_verified_device_saved
     */
    public function setIsVerifiedDeviceSaved(?bool $isVerifiedDeviceSaved): void
    {
        $this->isVerifiedDeviceSaved = $isVerifiedDeviceSaved;
    }

    /**
     * Returns Redirect Url.
     */
    public function getRedirectUrl(): ?string
    {
        return $this->redirectUrl;
    }

    /**
     * Sets Redirect Url.
     *
     * @maps redirect_url
     */
    public function setRedirectUrl(?string $redirectUrl): void
    {
        $this->redirectUrl = $redirectUrl;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->transaction)) {
            $json['transaction']              = $this->transaction;
        }
        if (isset($this->externalOutputs)) {
            $json['external_outputs']         = $this->externalOutputs;
        }
        if (isset($this->isVerifiedDeviceSaved)) {
            $json['is_verified_device_saved'] = $this->isVerifiedDeviceSaved;
        }
        if (isset($this->redirectUrl)) {
            $json['redirect_url']             = $this->redirectUrl;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
