<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class IDeliveryOptions implements \JsonSerializable
{
    /**
     * @var IStoreShipmentView[]|null
     */
    private $inStorePickupOptions;

    /**
     * @var ICartShipmentView[]|null
     */
    private $shippingOptions;

    /**
     * @var IStoreShipmentView[]|null
     */
    private $shipToStoreOptions;

    /**
     * @var IOrderDynamicContent|null
     */
    private $dynamicContent;

    /**
     * Returns In Store Pickup Options.
     *
     * @return IStoreShipmentView[]|null
     */
    public function getInStorePickupOptions(): ?array
    {
        return $this->inStorePickupOptions;
    }

    /**
     * Sets In Store Pickup Options.
     *
     * @maps inStorePickupOptions
     *
     * @param IStoreShipmentView[]|null $inStorePickupOptions
     */
    public function setInStorePickupOptions(?array $inStorePickupOptions): void
    {
        $this->inStorePickupOptions = $inStorePickupOptions;
    }

    /**
     * Returns Shipping Options.
     *
     * @return ICartShipmentView[]|null
     */
    public function getShippingOptions(): ?array
    {
        return $this->shippingOptions;
    }

    /**
     * Sets Shipping Options.
     *
     * @maps shippingOptions
     *
     * @param ICartShipmentView[]|null $shippingOptions
     */
    public function setShippingOptions(?array $shippingOptions): void
    {
        $this->shippingOptions = $shippingOptions;
    }

    /**
     * Returns Ship to Store Options.
     *
     * @return IStoreShipmentView[]|null
     */
    public function getShipToStoreOptions(): ?array
    {
        return $this->shipToStoreOptions;
    }

    /**
     * Sets Ship to Store Options.
     *
     * @maps shipToStoreOptions
     *
     * @param IStoreShipmentView[]|null $shipToStoreOptions
     */
    public function setShipToStoreOptions(?array $shipToStoreOptions): void
    {
        $this->shipToStoreOptions = $shipToStoreOptions;
    }

    /**
     * Returns Dynamic Content.
     */
    public function getDynamicContent(): ?IOrderDynamicContent
    {
        return $this->dynamicContent;
    }

    /**
     * Sets Dynamic Content.
     *
     * @maps dynamicContent
     */
    public function setDynamicContent(?IOrderDynamicContent $dynamicContent): void
    {
        $this->dynamicContent = $dynamicContent;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->inStorePickupOptions)) {
            $json['inStorePickupOptions'] = $this->inStorePickupOptions;
        }
        if (isset($this->shippingOptions)) {
            $json['shippingOptions']      = $this->shippingOptions;
        }
        if (isset($this->shipToStoreOptions)) {
            $json['shipToStoreOptions']   = $this->shipToStoreOptions;
        }
        if (isset($this->dynamicContent)) {
            $json['dynamicContent']       = $this->dynamicContent;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
