<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class IDescriptionPart implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $isHtml;

    /**
     * @var string|null
     */
    private $content;

    /**
     * Returns Is Html.
     */
    public function getIsHtml(): ?bool
    {
        return $this->isHtml;
    }

    /**
     * Sets Is Html.
     *
     * @maps is_html
     */
    public function setIsHtml(?bool $isHtml): void
    {
        $this->isHtml = $isHtml;
    }

    /**
     * Returns Content.
     */
    public function getContent(): ?string
    {
        return $this->content;
    }

    /**
     * Sets Content.
     *
     * @maps content
     */
    public function setContent(?string $content): void
    {
        $this->content = $content;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->isHtml)) {
            $json['is_html'] = $this->isHtml;
        }
        if (isset($this->content)) {
            $json['content'] = $this->content;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
