<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class IGiftOptionView implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $hideGiftMessage;

    /**
     * @var bool|null
     */
    private $hideGiftWrap;

    /**
     * Returns Hide Gift Message.
     */
    public function getHideGiftMessage(): ?bool
    {
        return $this->hideGiftMessage;
    }

    /**
     * Sets Hide Gift Message.
     *
     * @maps hide_gift_message
     */
    public function setHideGiftMessage(?bool $hideGiftMessage): void
    {
        $this->hideGiftMessage = $hideGiftMessage;
    }

    /**
     * Returns Hide Gift Wrap.
     */
    public function getHideGiftWrap(): ?bool
    {
        return $this->hideGiftWrap;
    }

    /**
     * Sets Hide Gift Wrap.
     *
     * @maps hide_gift_wrap
     */
    public function setHideGiftWrap(?bool $hideGiftWrap): void
    {
        $this->hideGiftWrap = $hideGiftWrap;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->hideGiftMessage)) {
            $json['hide_gift_message'] = $this->hideGiftMessage;
        }
        if (isset($this->hideGiftWrap)) {
            $json['hide_gift_wrap']    = $this->hideGiftWrap;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
