<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

class IndemnificationReasonEnum
{
    public const CHECKOUT = 'checkout';

    public const ANALYST_APPROVED = 'analyst_approved';

    public const VIRTUAL_TERMINAL = 'virtual_terminal';

    public const MERCHANT_BACK_OFFICE = 'merchant_back_office';

    public const MERCHANT_FORCE_APPROVED = 'merchant_force_approved';

    public const REVERSIBLY_REJECTED = 'reversibly_rejected';

    public const IRREVERSIBLY_REJECTED = 'irreversibly_rejected';

    public const RISK_ENGINE_APPROVED = 'risk_engine_approved';

    public const AUTH_VERIFICATION = 'auth_verification';

    public const PAYPAL = 'paypal';

    public const AFTERPAY = 'afterpay';

    public const DIRECT_PAYMENTS = 'direct_payments';

    public const EXTERNAL_REVIEW = 'external_review';

    public const AFFIRM = 'affirm';

    public const PHONE_ORDER = 'phone_order';

    public const AMAZON_PAY = 'amazon_pay';

    public const KLARNA = 'klarna';

    public const INDEMNIFY_DIRECT_PAYMENTS = 'indemnify_direct_payments';

    public const MEMBERSHIP_SUBSCRIPTION = 'membership_subscription';

    public const MERCHANT_IP_ADDRESS = 'merchant_ip_address';
}
