<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class IProductInventory implements \JsonSerializable
{
    /**
     * @var IProduct|null
     */
    private $current;

    /**
     * @var IProduct|null
     */
    private $parent;

    /**
     * @var IProduct[]|null
     */
    private $properties;

    /**
     * @var IProduct[]|null
     */
    private $variants;

    /**
     * @var string|null
     */
    private $nextCursor;

    /**
     * Returns Current.
     */
    public function getCurrent(): ?IProduct
    {
        return $this->current;
    }

    /**
     * Sets Current.
     *
     * @maps Current
     */
    public function setCurrent(?IProduct $current): void
    {
        $this->current = $current;
    }

    /**
     * Returns Parent.
     */
    public function getParent(): ?IProduct
    {
        return $this->parent;
    }

    /**
     * Sets Parent.
     *
     * @maps Parent
     */
    public function setParent(?IProduct $parent): void
    {
        $this->parent = $parent;
    }

    /**
     * Returns Properties.
     *
     * @return IProduct[]|null
     */
    public function getProperties(): ?array
    {
        return $this->properties;
    }

    /**
     * Sets Properties.
     *
     * @maps Properties
     *
     * @param IProduct[]|null $properties
     */
    public function setProperties(?array $properties): void
    {
        $this->properties = $properties;
    }

    /**
     * Returns Variants.
     *
     * @return IProduct[]|null
     */
    public function getVariants(): ?array
    {
        return $this->variants;
    }

    /**
     * Sets Variants.
     *
     * @maps Variants
     *
     * @param IProduct[]|null $variants
     */
    public function setVariants(?array $variants): void
    {
        $this->variants = $variants;
    }

    /**
     * Returns Next Cursor.
     */
    public function getNextCursor(): ?string
    {
        return $this->nextCursor;
    }

    /**
     * Sets Next Cursor.
     *
     * @maps NextCursor
     */
    public function setNextCursor(?string $nextCursor): void
    {
        $this->nextCursor = $nextCursor;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->current)) {
            $json['Current']    = $this->current;
        }
        if (isset($this->parent)) {
            $json['Parent']     = $this->parent;
        }
        if (isset($this->properties)) {
            $json['Properties'] = $this->properties;
        }
        if (isset($this->variants)) {
            $json['Variants']   = $this->variants;
        }
        if (isset($this->nextCursor)) {
            $json['NextCursor'] = $this->nextCursor;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
