<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class MerchantDivisionSummaryView implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $merchantId;

    /**
     * @var string|null
     */
    private $publicId;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var string|null
     */
    private $displayName;

    /**
     * @var MerchantDivisionLogoView|null
     */
    private $logo;

    /**
     * @var MerchantDivisionLogoView|null
     */
    private $logoDashboard;

    /**
     * @var string|null
     */
    private $platform;

    /**
     * @var string|null
     */
    private $hookUrl;

    /**
     * @var int|null
     */
    private $hookType;

    /**
     * @var bool|null
     */
    private $isUniversalMerchantApi;

    /**
     * @var bool|null
     */
    private $isWebhooksV2;

    /**
     * @var string[]|null
     */
    private $webhookUrls;

    /**
     * @var string|null
     */
    private $supportPageUrl;

    /**
     * @var string|null
     */
    private $shippingAndTaxUrl;

    /**
     * @var string|null
     */
    private $universalMerchantApiUrl;

    /**
     * @var string|null
     */
    private $accountPageUrl;

    /**
     * @var string|null
     */
    private $oauthRedirectUrl;

    /**
     * @var string|null
     */
    private $mobileAppDomainUrl;

    /**
     * @var string|null
     */
    private $oauthLogoutUrl;

    /**
     * @var string|null
     */
    private $getAccountUrl;

    /**
     * @var string|null
     */
    private $validateAdditionalAccountDataUrl;

    /**
     * @var string|null
     */
    private $termsOfServiceUrl;

    /**
     * @var string|null
     */
    private $privacyPolicyUrl;

    /**
     * @var string|null
     */
    private $productInfoUrl;

    /**
     * @var string|null
     */
    private $merchantSmsNumber;

    /**
     * @var string|null
     */
    private $merchantSmsAutoreply;

    /**
     * @var bool|null
     */
    private $isProvisioned;

    /**
     * @var string|null
     */
    private $iosAppName;

    /**
     * @var string|null
     */
    private $shippingUrl;

    /**
     * @var string|null
     */
    private $taxUrl;

    /**
     * @var string|null
     */
    private $updateCartUrl;

    /**
     * @var string|null
     */
    private $debugUrl;

    /**
     * @var string|null
     */
    private $sfccSiteId;

    /**
     * Returns Id.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Merchant Id.
     */
    public function getMerchantId(): ?string
    {
        return $this->merchantId;
    }

    /**
     * Sets Merchant Id.
     *
     * @maps merchant_id
     */
    public function setMerchantId(?string $merchantId): void
    {
        $this->merchantId = $merchantId;
    }

    /**
     * Returns Public Id.
     */
    public function getPublicId(): ?string
    {
        return $this->publicId;
    }

    /**
     * Sets Public Id.
     *
     * @maps public_id
     */
    public function setPublicId(?string $publicId): void
    {
        $this->publicId = $publicId;
    }

    /**
     * Returns Description.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Display Name.
     */
    public function getDisplayName(): ?string
    {
        return $this->displayName;
    }

    /**
     * Sets Display Name.
     *
     * @maps display_name
     */
    public function setDisplayName(?string $displayName): void
    {
        $this->displayName = $displayName;
    }

    /**
     * Returns Logo.
     */
    public function getLogo(): ?MerchantDivisionLogoView
    {
        return $this->logo;
    }

    /**
     * Sets Logo.
     *
     * @maps logo
     */
    public function setLogo(?MerchantDivisionLogoView $logo): void
    {
        $this->logo = $logo;
    }

    /**
     * Returns Logo Dashboard.
     */
    public function getLogoDashboard(): ?MerchantDivisionLogoView
    {
        return $this->logoDashboard;
    }

    /**
     * Sets Logo Dashboard.
     *
     * @maps logo_dashboard
     */
    public function setLogoDashboard(?MerchantDivisionLogoView $logoDashboard): void
    {
        $this->logoDashboard = $logoDashboard;
    }

    /**
     * Returns Platform.
     */
    public function getPlatform(): ?string
    {
        return $this->platform;
    }

    /**
     * Sets Platform.
     *
     * @maps platform
     */
    public function setPlatform(?string $platform): void
    {
        $this->platform = $platform;
    }

    /**
     * Returns Hook Url.
     */
    public function getHookUrl(): ?string
    {
        return $this->hookUrl;
    }

    /**
     * Sets Hook Url.
     *
     * @maps hook_url
     */
    public function setHookUrl(?string $hookUrl): void
    {
        $this->hookUrl = $hookUrl;
    }

    /**
     * Returns Hook Type.
     */
    public function getHookType(): ?int
    {
        return $this->hookType;
    }

    /**
     * Sets Hook Type.
     *
     * @maps hook_type
     */
    public function setHookType(?int $hookType): void
    {
        $this->hookType = $hookType;
    }

    /**
     * Returns Is Universal Merchant Api.
     */
    public function getIsUniversalMerchantApi(): ?bool
    {
        return $this->isUniversalMerchantApi;
    }

    /**
     * Sets Is Universal Merchant Api.
     *
     * @maps is_universal_merchant_api
     */
    public function setIsUniversalMerchantApi(?bool $isUniversalMerchantApi): void
    {
        $this->isUniversalMerchantApi = $isUniversalMerchantApi;
    }

    /**
     * Returns Is Webhooks V2.
     */
    public function getIsWebhooksV2(): ?bool
    {
        return $this->isWebhooksV2;
    }

    /**
     * Sets Is Webhooks V2.
     *
     * @maps is_webhooks_v2
     */
    public function setIsWebhooksV2(?bool $isWebhooksV2): void
    {
        $this->isWebhooksV2 = $isWebhooksV2;
    }

    /**
     * Returns Webhook Urls.
     *
     * @return string[]|null
     */
    public function getWebhookUrls(): ?array
    {
        return $this->webhookUrls;
    }

    /**
     * Sets Webhook Urls.
     *
     * @maps webhook_urls
     *
     * @param string[]|null $webhookUrls
     */
    public function setWebhookUrls(?array $webhookUrls): void
    {
        $this->webhookUrls = $webhookUrls;
    }

    /**
     * Returns Support Page Url.
     */
    public function getSupportPageUrl(): ?string
    {
        return $this->supportPageUrl;
    }

    /**
     * Sets Support Page Url.
     *
     * @maps support_page_url
     */
    public function setSupportPageUrl(?string $supportPageUrl): void
    {
        $this->supportPageUrl = $supportPageUrl;
    }

    /**
     * Returns Shipping and Tax Url.
     */
    public function getShippingAndTaxUrl(): ?string
    {
        return $this->shippingAndTaxUrl;
    }

    /**
     * Sets Shipping and Tax Url.
     *
     * @maps shipping_and_tax_url
     */
    public function setShippingAndTaxUrl(?string $shippingAndTaxUrl): void
    {
        $this->shippingAndTaxUrl = $shippingAndTaxUrl;
    }

    /**
     * Returns Universal Merchant Api Url.
     */
    public function getUniversalMerchantApiUrl(): ?string
    {
        return $this->universalMerchantApiUrl;
    }

    /**
     * Sets Universal Merchant Api Url.
     *
     * @maps universal_merchant_api_url
     */
    public function setUniversalMerchantApiUrl(?string $universalMerchantApiUrl): void
    {
        $this->universalMerchantApiUrl = $universalMerchantApiUrl;
    }

    /**
     * Returns Account Page Url.
     */
    public function getAccountPageUrl(): ?string
    {
        return $this->accountPageUrl;
    }

    /**
     * Sets Account Page Url.
     *
     * @maps account_page_url
     */
    public function setAccountPageUrl(?string $accountPageUrl): void
    {
        $this->accountPageUrl = $accountPageUrl;
    }

    /**
     * Returns Oauth Redirect Url.
     */
    public function getOauthRedirectUrl(): ?string
    {
        return $this->oauthRedirectUrl;
    }

    /**
     * Sets Oauth Redirect Url.
     *
     * @maps oauth_redirect_url
     */
    public function setOauthRedirectUrl(?string $oauthRedirectUrl): void
    {
        $this->oauthRedirectUrl = $oauthRedirectUrl;
    }

    /**
     * Returns Mobile App Domain Url.
     */
    public function getMobileAppDomainUrl(): ?string
    {
        return $this->mobileAppDomainUrl;
    }

    /**
     * Sets Mobile App Domain Url.
     *
     * @maps mobile_app_domain_url
     */
    public function setMobileAppDomainUrl(?string $mobileAppDomainUrl): void
    {
        $this->mobileAppDomainUrl = $mobileAppDomainUrl;
    }

    /**
     * Returns Oauth Logout Url.
     */
    public function getOauthLogoutUrl(): ?string
    {
        return $this->oauthLogoutUrl;
    }

    /**
     * Sets Oauth Logout Url.
     *
     * @maps oauth_logout_url
     */
    public function setOauthLogoutUrl(?string $oauthLogoutUrl): void
    {
        $this->oauthLogoutUrl = $oauthLogoutUrl;
    }

    /**
     * Returns Get Account Url.
     */
    public function getGetAccountUrl(): ?string
    {
        return $this->getAccountUrl;
    }

    /**
     * Sets Get Account Url.
     *
     * @maps get_account_url
     */
    public function setGetAccountUrl(?string $getAccountUrl): void
    {
        $this->getAccountUrl = $getAccountUrl;
    }

    /**
     * Returns Validate Additional Account Data Url.
     */
    public function getValidateAdditionalAccountDataUrl(): ?string
    {
        return $this->validateAdditionalAccountDataUrl;
    }

    /**
     * Sets Validate Additional Account Data Url.
     *
     * @maps validate_additional_account_data_url
     */
    public function setValidateAdditionalAccountDataUrl(?string $validateAdditionalAccountDataUrl): void
    {
        $this->validateAdditionalAccountDataUrl = $validateAdditionalAccountDataUrl;
    }

    /**
     * Returns Terms of Service Url.
     */
    public function getTermsOfServiceUrl(): ?string
    {
        return $this->termsOfServiceUrl;
    }

    /**
     * Sets Terms of Service Url.
     *
     * @maps terms_of_service_url
     */
    public function setTermsOfServiceUrl(?string $termsOfServiceUrl): void
    {
        $this->termsOfServiceUrl = $termsOfServiceUrl;
    }

    /**
     * Returns Privacy Policy Url.
     */
    public function getPrivacyPolicyUrl(): ?string
    {
        return $this->privacyPolicyUrl;
    }

    /**
     * Sets Privacy Policy Url.
     *
     * @maps privacy_policy_url
     */
    public function setPrivacyPolicyUrl(?string $privacyPolicyUrl): void
    {
        $this->privacyPolicyUrl = $privacyPolicyUrl;
    }

    /**
     * Returns Product Info Url.
     */
    public function getProductInfoUrl(): ?string
    {
        return $this->productInfoUrl;
    }

    /**
     * Sets Product Info Url.
     *
     * @maps product_info_url
     */
    public function setProductInfoUrl(?string $productInfoUrl): void
    {
        $this->productInfoUrl = $productInfoUrl;
    }

    /**
     * Returns Merchant Sms Number.
     */
    public function getMerchantSmsNumber(): ?string
    {
        return $this->merchantSmsNumber;
    }

    /**
     * Sets Merchant Sms Number.
     *
     * @maps merchant_sms_number
     */
    public function setMerchantSmsNumber(?string $merchantSmsNumber): void
    {
        $this->merchantSmsNumber = $merchantSmsNumber;
    }

    /**
     * Returns Merchant Sms Autoreply.
     */
    public function getMerchantSmsAutoreply(): ?string
    {
        return $this->merchantSmsAutoreply;
    }

    /**
     * Sets Merchant Sms Autoreply.
     *
     * @maps merchant_sms_autoreply
     */
    public function setMerchantSmsAutoreply(?string $merchantSmsAutoreply): void
    {
        $this->merchantSmsAutoreply = $merchantSmsAutoreply;
    }

    /**
     * Returns Is Provisioned.
     */
    public function getIsProvisioned(): ?bool
    {
        return $this->isProvisioned;
    }

    /**
     * Sets Is Provisioned.
     *
     * @maps is_provisioned
     */
    public function setIsProvisioned(?bool $isProvisioned): void
    {
        $this->isProvisioned = $isProvisioned;
    }

    /**
     * Returns Ios App Name.
     */
    public function getIosAppName(): ?string
    {
        return $this->iosAppName;
    }

    /**
     * Sets Ios App Name.
     *
     * @maps ios_app_name
     */
    public function setIosAppName(?string $iosAppName): void
    {
        $this->iosAppName = $iosAppName;
    }

    /**
     * Returns Shipping Url.
     */
    public function getShippingUrl(): ?string
    {
        return $this->shippingUrl;
    }

    /**
     * Sets Shipping Url.
     *
     * @maps shipping_url
     */
    public function setShippingUrl(?string $shippingUrl): void
    {
        $this->shippingUrl = $shippingUrl;
    }

    /**
     * Returns Tax Url.
     */
    public function getTaxUrl(): ?string
    {
        return $this->taxUrl;
    }

    /**
     * Sets Tax Url.
     *
     * @maps tax_url
     */
    public function setTaxUrl(?string $taxUrl): void
    {
        $this->taxUrl = $taxUrl;
    }

    /**
     * Returns Update Cart Url.
     */
    public function getUpdateCartUrl(): ?string
    {
        return $this->updateCartUrl;
    }

    /**
     * Sets Update Cart Url.
     *
     * @maps update_cart_url
     */
    public function setUpdateCartUrl(?string $updateCartUrl): void
    {
        $this->updateCartUrl = $updateCartUrl;
    }

    /**
     * Returns Debug Url.
     */
    public function getDebugUrl(): ?string
    {
        return $this->debugUrl;
    }

    /**
     * Sets Debug Url.
     *
     * @maps debug_url
     */
    public function setDebugUrl(?string $debugUrl): void
    {
        $this->debugUrl = $debugUrl;
    }

    /**
     * Returns Sfcc Site Id.
     */
    public function getSfccSiteId(): ?string
    {
        return $this->sfccSiteId;
    }

    /**
     * Sets Sfcc Site Id.
     *
     * @maps sfcc_site_id
     */
    public function setSfccSiteId(?string $sfccSiteId): void
    {
        $this->sfccSiteId = $sfccSiteId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']                                   = $this->id;
        }
        if (isset($this->merchantId)) {
            $json['merchant_id']                          = $this->merchantId;
        }
        if (isset($this->publicId)) {
            $json['public_id']                            = $this->publicId;
        }
        if (isset($this->description)) {
            $json['description']                          = $this->description;
        }
        if (isset($this->displayName)) {
            $json['display_name']                         = $this->displayName;
        }
        if (isset($this->logo)) {
            $json['logo']                                 = $this->logo;
        }
        if (isset($this->logoDashboard)) {
            $json['logo_dashboard']                       = $this->logoDashboard;
        }
        if (isset($this->platform)) {
            $json['platform']                             = $this->platform;
        }
        if (isset($this->hookUrl)) {
            $json['hook_url']                             = $this->hookUrl;
        }
        if (isset($this->hookType)) {
            $json['hook_type']                            = $this->hookType;
        }
        if (isset($this->isUniversalMerchantApi)) {
            $json['is_universal_merchant_api']            = $this->isUniversalMerchantApi;
        }
        if (isset($this->isWebhooksV2)) {
            $json['is_webhooks_v2']                       = $this->isWebhooksV2;
        }
        if (isset($this->webhookUrls)) {
            $json['webhook_urls']                         = $this->webhookUrls;
        }
        if (isset($this->supportPageUrl)) {
            $json['support_page_url']                     = $this->supportPageUrl;
        }
        if (isset($this->shippingAndTaxUrl)) {
            $json['shipping_and_tax_url']                 = $this->shippingAndTaxUrl;
        }
        if (isset($this->universalMerchantApiUrl)) {
            $json['universal_merchant_api_url']           = $this->universalMerchantApiUrl;
        }
        if (isset($this->accountPageUrl)) {
            $json['account_page_url']                     = $this->accountPageUrl;
        }
        if (isset($this->oauthRedirectUrl)) {
            $json['oauth_redirect_url']                   = $this->oauthRedirectUrl;
        }
        if (isset($this->mobileAppDomainUrl)) {
            $json['mobile_app_domain_url']                = $this->mobileAppDomainUrl;
        }
        if (isset($this->oauthLogoutUrl)) {
            $json['oauth_logout_url']                     = $this->oauthLogoutUrl;
        }
        if (isset($this->getAccountUrl)) {
            $json['get_account_url']                      = $this->getAccountUrl;
        }
        if (isset($this->validateAdditionalAccountDataUrl)) {
            $json['validate_additional_account_data_url'] = $this->validateAdditionalAccountDataUrl;
        }
        if (isset($this->termsOfServiceUrl)) {
            $json['terms_of_service_url']                 = $this->termsOfServiceUrl;
        }
        if (isset($this->privacyPolicyUrl)) {
            $json['privacy_policy_url']                   = $this->privacyPolicyUrl;
        }
        if (isset($this->productInfoUrl)) {
            $json['product_info_url']                     = $this->productInfoUrl;
        }
        if (isset($this->merchantSmsNumber)) {
            $json['merchant_sms_number']                  = $this->merchantSmsNumber;
        }
        if (isset($this->merchantSmsAutoreply)) {
            $json['merchant_sms_autoreply']               = $this->merchantSmsAutoreply;
        }
        if (isset($this->isProvisioned)) {
            $json['is_provisioned']                       = $this->isProvisioned;
        }
        if (isset($this->iosAppName)) {
            $json['ios_app_name']                         = $this->iosAppName;
        }
        if (isset($this->shippingUrl)) {
            $json['shipping_url']                         = $this->shippingUrl;
        }
        if (isset($this->taxUrl)) {
            $json['tax_url']                              = $this->taxUrl;
        }
        if (isset($this->updateCartUrl)) {
            $json['update_cart_url']                      = $this->updateCartUrl;
        }
        if (isset($this->debugUrl)) {
            $json['debug_url']                            = $this->debugUrl;
        }
        if (isset($this->sfccSiteId)) {
            $json['sfcc_site_id']                         = $this->sfccSiteId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
