<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class MerchantView implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $createdAt;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var string|null
     */
    private $processor;

    /**
     * @var OperationalProcessor[]|null
     */
    private $operationalProcessors;

    /**
     * @var string|null
     */
    private $publicId;

    /**
     * @var string|null
     */
    private $timeZone;

    /**
     * @var string|null
     */
    private $onboardingStatus;

    /**
     * Returns Created At.
     */
    public function getCreatedAt(): ?string
    {
        return $this->createdAt;
    }

    /**
     * Sets Created At.
     *
     * @maps created_at
     */
    public function setCreatedAt(?string $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Returns Description.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Processor.
     */
    public function getProcessor(): ?string
    {
        return $this->processor;
    }

    /**
     * Sets Processor.
     *
     * @maps processor
     */
    public function setProcessor(?string $processor): void
    {
        $this->processor = $processor;
    }

    /**
     * Returns Operational Processors.
     *
     * @return OperationalProcessor[]|null
     */
    public function getOperationalProcessors(): ?array
    {
        return $this->operationalProcessors;
    }

    /**
     * Sets Operational Processors.
     *
     * @maps operational_processors
     *
     * @param OperationalProcessor[]|null $operationalProcessors
     */
    public function setOperationalProcessors(?array $operationalProcessors): void
    {
        $this->operationalProcessors = $operationalProcessors;
    }

    /**
     * Returns Public Id.
     */
    public function getPublicId(): ?string
    {
        return $this->publicId;
    }

    /**
     * Sets Public Id.
     *
     * @maps public_id
     */
    public function setPublicId(?string $publicId): void
    {
        $this->publicId = $publicId;
    }

    /**
     * Returns Time Zone.
     */
    public function getTimeZone(): ?string
    {
        return $this->timeZone;
    }

    /**
     * Sets Time Zone.
     *
     * @maps time_zone
     */
    public function setTimeZone(?string $timeZone): void
    {
        $this->timeZone = $timeZone;
    }

    /**
     * Returns Onboarding Status.
     */
    public function getOnboardingStatus(): ?string
    {
        return $this->onboardingStatus;
    }

    /**
     * Sets Onboarding Status.
     *
     * @maps onboarding_status
     */
    public function setOnboardingStatus(?string $onboardingStatus): void
    {
        $this->onboardingStatus = $onboardingStatus;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->createdAt)) {
            $json['created_at']             = $this->createdAt;
        }
        if (isset($this->description)) {
            $json['description']            = $this->description;
        }
        if (isset($this->processor)) {
            $json['processor']              = $this->processor;
        }
        if (isset($this->operationalProcessors)) {
            $json['operational_processors'] = $this->operationalProcessors;
        }
        if (isset($this->publicId)) {
            $json['public_id']              = $this->publicId;
        }
        if (isset($this->timeZone)) {
            $json['time_zone']              = $this->timeZone;
        }
        if (isset($this->onboardingStatus)) {
            $json['onboarding_status']      = $this->onboardingStatus;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
