<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class MerchantMetrics implements \JsonSerializable
{
    /**
     * @var Metric[]|null
     */
    private $metrics;

    /**
     * Returns Metrics.
     *
     * @return Metric[]|null
     */
    public function getMetrics(): ?array
    {
        return $this->metrics;
    }

    /**
     * Sets Metrics.
     *
     * @maps metrics
     *
     * @param Metric[]|null $metrics
     */
    public function setMetrics(?array $metrics): void
    {
        $this->metrics = $metrics;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->metrics)) {
            $json['metrics'] = $this->metrics;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
