<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

class MethodEnum
{
    public const CODE = 'code';

    public const CODE_PASSWORD = 'code_password';

    public const PASSWORD = 'password';

    public const ROTATE_PASSWORD = 'rotate_password';
}
