<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

class NetworkEnum
{
    public const UNKNOWN = 'unknown';

    public const VISA = 'visa';

    public const MASTERCARD = 'mastercard';

    public const AMEX = 'amex';

    public const DISCOVER = 'discover';

    public const JCB = 'jcb';

    public const UNIONPAY = 'unionpay';

    public const CVV = 'cvv';

    public const ALLIANCEDATA = 'alliancedata';

    public const CITIPLCC = 'citiplcc';
}
