<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class OrderCreateExternalInputs implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $shopifyRequest;

    /**
     * Returns Shopify Request.
     */
    public function getShopifyRequest(): ?string
    {
        return $this->shopifyRequest;
    }

    /**
     * Sets Shopify Request.
     *
     * @maps shopify_request
     */
    public function setShopifyRequest(?string $shopifyRequest): void
    {
        $this->shopifyRequest = $shopifyRequest;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->shopifyRequest)) {
            $json['shopify_request'] = $this->shopifyRequest;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
