<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class OrderDecisionDetailsView implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $score;

    /**
     * @var string[]|null
     */
    private $decisionFactors;

    /**
     * Returns Score.
     */
    public function getScore(): ?int
    {
        return $this->score;
    }

    /**
     * Sets Score.
     *
     * @maps score
     */
    public function setScore(?int $score): void
    {
        $this->score = $score;
    }

    /**
     * Returns Decision Factors.
     *
     * @return string[]|null
     */
    public function getDecisionFactors(): ?array
    {
        return $this->decisionFactors;
    }

    /**
     * Sets Decision Factors.
     *
     * @maps decision_factors
     *
     * @param string[]|null $decisionFactors
     */
    public function setDecisionFactors(?array $decisionFactors): void
    {
        $this->decisionFactors = $decisionFactors;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->score)) {
            $json['score']            = $this->score;
        }
        if (isset($this->decisionFactors)) {
            $json['decision_factors'] = $this->decisionFactors;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
