<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class OrderView implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $token;

    /**
     * @var CartView|null
     */
    private $cart;

    /**
     * @var OrderExternalDataView|null
     */
    private $externalData;

    /**
     * @var string|null
     */
    private $userNote;

    /**
     * @var IOrderDynamicContent|null
     */
    private $dynamicContent;

    /**
     * Returns Token.
     */
    public function getToken(): ?string
    {
        return $this->token;
    }

    /**
     * Sets Token.
     *
     * @maps token
     */
    public function setToken(?string $token): void
    {
        $this->token = $token;
    }

    /**
     * Returns Cart.
     *
     * This is the cart object returned in a successful response.
     */
    public function getCart(): ?CartView
    {
        return $this->cart;
    }

    /**
     * Sets Cart.
     *
     * This is the cart object returned in a successful response.
     *
     * @maps cart
     */
    public function setCart(?CartView $cart): void
    {
        $this->cart = $cart;
    }

    /**
     * Returns External Data.
     */
    public function getExternalData(): ?OrderExternalDataView
    {
        return $this->externalData;
    }

    /**
     * Sets External Data.
     *
     * @maps external_data
     */
    public function setExternalData(?OrderExternalDataView $externalData): void
    {
        $this->externalData = $externalData;
    }

    /**
     * Returns User Note.
     *
     * Used by shoppers to make extra requests or provide details for gift messages.
     */
    public function getUserNote(): ?string
    {
        return $this->userNote;
    }

    /**
     * Sets User Note.
     *
     * Used by shoppers to make extra requests or provide details for gift messages.
     *
     * @maps user_note
     */
    public function setUserNote(?string $userNote): void
    {
        $this->userNote = $userNote;
    }

    /**
     * Returns Dynamic Content.
     */
    public function getDynamicContent(): ?IOrderDynamicContent
    {
        return $this->dynamicContent;
    }

    /**
     * Sets Dynamic Content.
     *
     * @maps dynamic_content
     */
    public function setDynamicContent(?IOrderDynamicContent $dynamicContent): void
    {
        $this->dynamicContent = $dynamicContent;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->token)) {
            $json['token']           = $this->token;
        }
        if (isset($this->cart)) {
            $json['cart']            = $this->cart;
        }
        if (isset($this->externalData)) {
            $json['external_data']   = $this->externalData;
        }
        if (isset($this->userNote)) {
            $json['user_note']       = $this->userNote;
        }
        if (isset($this->dynamicContent)) {
            $json['dynamic_content'] = $this->dynamicContent;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
