<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class OrderExternalDataView implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $steamId;

    /**
     * @var string|null
     */
    private $shopify;

    /**
     * Returns Steam Id.
     */
    public function getSteamId(): ?string
    {
        return $this->steamId;
    }

    /**
     * Sets Steam Id.
     *
     * @maps steam_id
     */
    public function setSteamId(?string $steamId): void
    {
        $this->steamId = $steamId;
    }

    /**
     * Returns Shopify.
     */
    public function getShopify(): ?string
    {
        return $this->shopify;
    }

    /**
     * Sets Shopify.
     *
     * @maps shopify
     */
    public function setShopify(?string $shopify): void
    {
        $this->shopify = $shopify;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->steamId)) {
            $json['steam_id'] = $this->steamId;
        }
        if (isset($this->shopify)) {
            $json['shopify']  = $this->shopify;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
