<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class PaymentMethod implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $paymentMethodProvider;

    /**
     * @var AllianceDataInfo|null
     */
    private $paymentMethodData;

    /**
     * Returns Payment Method Provider.
     */
    public function getPaymentMethodProvider(): ?string
    {
        return $this->paymentMethodProvider;
    }

    /**
     * Sets Payment Method Provider.
     *
     * @maps payment_method_provider
     */
    public function setPaymentMethodProvider(?string $paymentMethodProvider): void
    {
        $this->paymentMethodProvider = $paymentMethodProvider;
    }

    /**
     * Returns Payment Method Data.
     */
    public function getPaymentMethodData(): ?AllianceDataInfo
    {
        return $this->paymentMethodData;
    }

    /**
     * Sets Payment Method Data.
     *
     * @maps payment_method_data
     */
    public function setPaymentMethodData(?AllianceDataInfo $paymentMethodData): void
    {
        $this->paymentMethodData = $paymentMethodData;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->paymentMethodProvider)) {
            $json['payment_method_provider'] = $this->paymentMethodProvider;
        }
        if (isset($this->paymentMethodData)) {
            $json['payment_method_data']     = $this->paymentMethodData;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
