<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

class PaymentMethodProviderEnum
{
    public const ALLIANCE_DATA = 'alliance_data';
}
