<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class PaymentMethodSessionView implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $paymentMethodSession;

    /**
     * Returns Payment Method Session.
     */
    public function getPaymentMethodSession(): ?string
    {
        return $this->paymentMethodSession;
    }

    /**
     * Sets Payment Method Session.
     *
     * @maps payment_method_session
     */
    public function setPaymentMethodSession(?string $paymentMethodSession): void
    {
        $this->paymentMethodSession = $paymentMethodSession;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->paymentMethodSession)) {
            $json['payment_method_session'] = $this->paymentMethodSession;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
