<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

class PlatformAccountStatusEnum
{
    public const NONE = 'none';

    public const LINKED = 'linked';

    public const UNLINKED = 'unlinked';
}
