<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

class Processor1Enum
{
    public const VANTIV = 'vantiv';

    public const ADYEN_PAYFAC = 'adyen_payfac';

    public const ADYEN_GATEWAY = 'adyen_gateway';

    public const STRIPE = 'stripe';

    public const BRAINTREE = 'braintree';

    public const CYBERSOURCE = 'cybersource';

    public const NMI = 'nmi';

    public const AUTHORIZE_NET = 'authorize_net';

    public const RADIAL = 'radial';

    public const SHOPIFY_PAYMENTS = 'shopify_payments';

    public const ROCKETGATE = 'rocketgate';
}
