<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

class ProcessorEnum
{
    public const VANTIV = 'vantiv';

    public const STRIPE = 'stripe';

    public const BRAINTREE = 'braintree';

    public const CYBERSOURCE = 'cybersource';

    public const PAYPAL = 'paypal';

    public const AFTERPAY = 'afterpay';

    public const ADYEN_GATEWAY = 'adyen_gateway';

    public const ADYEN_PAYFAC = 'adyen_payfac';

    public const NMI = 'nmi';

    public const AFFIRM = 'affirm';

    public const ALLIANCE_DATA = 'alliance_data';

    public const ORBITAL = 'orbital';

    public const AMAZON_PAY = 'amazon_pay';

    public const AUTHORIZE_NET = 'authorize_net';

    public const FIRST_DATA = 'first_data';

    public const KLARNA = 'klarna';

    public const RADIAL = 'radial';

    public const RADIAL_KLARNA = 'radial_klarna';

    public const RADIAL_PAYPAL = 'radial_paypal';

    public const SHOPIFY_PAYMENTS = 'shopify_payments';

    public const ROCKETGATE = 'rocketgate';
}
