<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

/**
 * Determines who initiated the transaction (e.g. shopper, merchant) and how they did it (e.g.
 * recurring subscription, on-file card).
 */
class ProcessingInitiatorEnum
{
    public const INITIAL_CARD_ON_FILE = 'initial_card_on_file';

    public const INITIAL_RECURRING = 'initial_recurring';

    public const STORED_CARDHOLDER_INITIATED = 'stored_cardholder_initiated';

    public const STORED_MERCHANT_INITIATED = 'stored_merchant_initiated';

    public const FOLLOWING_RECURRING = 'following_recurring';

    public const CARDHOLDER_INITIATED = 'cardholder_initiated';

    public const RECURRING = 'recurring';
}
