<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

class RepresentmentResultEnum
{
    public const NONE = 'none';

    public const OPEN = 'open';

    public const LOST = 'lost';

    public const WON = 'won';
}
