<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

class ShipmentTypeEnum
{
    public const UNKNOWN = 'unknown';

    public const DOOR_DELIVERY = 'door_delivery';

    public const SHIP_TO_STORE = 'ship_to_store';

    public const IN_STORE_PICKUP = 'in_store_pickup';
}
