<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

class SourceEnum
{
    public const ADD_ON = 'add_on';

    public const CHECKOUT = 'checkout';

    public const UNKNOWN = 'unknown';
}
