<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

class Source1Enum
{
    public const DIRECT_PAYMENTS = 'direct_payments';

    public const VIRTUAL_TERMINAL = 'virtual_terminal';
}
