<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

class Status1Enum
{
    public const SUCCEEDED = 'succeeded';

    public const DECLINED = 'declined';

    public const ERROR = 'error';

    public const PENDING = 'pending';

    public const ENUM_IN_PROGRESS = 'in progress';
}
