<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class TBD implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $needsToBeDocumented;

    /**
     * Returns Needs to Be Documented.
     */
    public function getNeedsToBeDocumented(): ?string
    {
        return $this->needsToBeDocumented;
    }

    /**
     * Sets Needs to Be Documented.
     *
     * @maps needs_to_be_documented
     */
    public function setNeedsToBeDocumented(?string $needsToBeDocumented): void
    {
        $this->needsToBeDocumented = $needsToBeDocumented;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->needsToBeDocumented)) {
            $json['needs_to_be_documented'] = $this->needsToBeDocumented;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
