<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

/**
 * Used to define which payment processor generated the token for this credit card.
 */
class TokenTypeEnum
{
    public const VANTIV = 'vantiv';

    public const APPLEPAY = 'applepay';

    public const BOLT = 'bolt';

    public const STRIPE = 'stripe';

    public const PLCC = 'plcc';
}
