<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

/**
 * An item that is part of a trackable shipment.
 */
class TrackingInputItem implements \JsonSerializable
{
    /**
     * @var string
     */
    private $reference;

    /**
     * @var TrackingInputItemOption[]
     */
    private $options;

    /**
     * @param string $reference
     * @param TrackingInputItemOption[] $options
     */
    public function __construct(string $reference, array $options)
    {
        $this->reference = $reference;
        $this->options = $options;
    }

    /**
     * Returns Reference.
     *
     * The item's ID; used by Easypost.
     */
    public function getReference(): string
    {
        return $this->reference;
    }

    /**
     * Sets Reference.
     *
     * The item's ID; used by Easypost.
     *
     * @required
     * @maps reference
     */
    public function setReference(string $reference): void
    {
        $this->reference = $reference;
    }

    /**
     * Returns Options.
     *
     * Used to map [Easypost shipment option objects](https://www.easypost.com/docs/api#options) to the
     * Easypost API.
     *
     * @return TrackingInputItemOption[]
     */
    public function getOptions(): array
    {
        return $this->options;
    }

    /**
     * Sets Options.
     *
     * Used to map [Easypost shipment option objects](https://www.easypost.com/docs/api#options) to the
     * Easypost API.
     *
     * @required
     * @maps options
     *
     * @param TrackingInputItemOption[] $options
     */
    public function setOptions(array $options): void
    {
        $this->options = $options;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['reference'] = $this->reference;
        $json['options']   = $this->options;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
