<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

/**
 * The type of statement. The type is prepended with a prefix containing the frequency of the
 * statement. The prefix will be either daily or monthly. Transaction statements will contain all
 * transactional event entries. Funding statements contain only funding transactional event entries.
 */
class Type9Enum
{
    public const DAILY_TRANSACTION = 'daily_transaction';

    public const MONTHLY_TRANSACTION = 'monthly_transaction';

    public const DAILY_FUNDING = 'daily_funding';
}
