<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

class Type2Enum
{
    public const UNKNOWN = 'unknown';

    public const DIGITAL = 'digital';

    public const PHYSICAL = 'physical';

    public const BUNDLED = 'bundled';
}
