<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

use stdClass;

class V1AccountsView implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $hasBoltAccount;

    /**
     * Returns Has Bolt Account.
     */
    public function getHasBoltAccount(): ?bool
    {
        return $this->hasBoltAccount;
    }

    /**
     * Sets Has Bolt Account.
     *
     * @maps has_bolt_account
     */
    public function setHasBoltAccount(?bool $hasBoltAccount): void
    {
        $this->hasBoltAccount = $hasBoltAccount;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->hasBoltAccount)) {
            $json['has_bolt_account'] = $this->hasBoltAccount;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
