<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

class ViewStatusEnum
{
    public const NOT_VIEWED = 'not_viewed';

    public const VIEWED = 'viewed';

    public const VIEWING = 'viewing';
}
