<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

/**
 * Determines why the transaction was voided.
 */
class VoidCauseEnum
{
    public const MERCHANT_ACTION = 'merchant_action';

    public const SHOPIFY_SYNC = 'shopify_sync';

    public const PAYPAL_SYNC = 'paypal_sync';

    public const AMAZON_PAY_SYNC = 'amazon_pay_sync';

    public const IRREVERSIBLE_REJECT = 'irreversible_reject';

    public const AUTH_EXPIRE = 'auth_expire';

    public const AUTH_VERIFICATION_EXPIRED = 'auth_verification_expired';

    public const PAYMENT_METHOD_UPDATER = 'payment_method_updater';
}
