<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib\Models;

class XResultEnum
{
    public const COMPLETED = 'completed';

    public const FAILED = 'failed';

    public const PENDING = 'pending';
}
