<?php

declare(strict_types=1);

/*
 * BoltAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace BoltAPILib;

/**
 * Environments available for API
 */
class Environment
{
    /**
     * SwaggerHub API Auto Mocking
     */
    public const PRODUCTION = 'production';

    /**
     * The Production URL (Live Data).
     */
    public const ENVIRONMENT2 = 'environment2';

    /**
     * The Sandbox URL (Test Data).
     */
    public const ENVIRONMENT3 = 'environment3';

    /**
     * The Staging URL (Staged Data).
     */
    public const ENVIRONMENT4 = 'environment4';
}
